version: '3'
services:
  node:
    restart: always
    build: .
    volumes:
      - ./:/code
    env_file:
      - .env_prod
  mongo:
    image: mongo
    command: mongod --quiet  --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
